name: morning_weakers
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: 0.7.1
  flutter_state_notifier: 0.4.2
  state_notifier: 0.5.0
  json_serializable: 3.3.0
  provider: 4.1.3

  firebase_core: 0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.0.14
  cloud_firestore: 0.13.6
  firebase_storage: 3.1.6

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  build_runner: 1.10.0
  freezed: 0.10.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/btn_google_signin/light/normal.png
    - assets/images/
